pipeline {
	agent any

	stages {
		stage ('Compile Stage') {
			sptes {
				withMaven(maven : 'maven_3_5_0') {
					sh 'mvn clean compile'
				}
			}
		}

		stage ('Testing Stage') {
			sptes {
				withMaven(maven : 'maven_3_5_0') {
					sh 'mvn test'
				}
			}
		}

		stage ('Deployment Stage') {
			sptes {
				withMaven(maven : 'maven_3_5_0') {
					sh 'mvn deploy'
				}
			}
		}
	}
}